---
# Source: prometheus-operator/charts/grafana/templates/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: promethues-operator-grafana
  namespace: monitoring
  labels:
    app: grafana
    chart: grafana-3.7.3
    release: promethues-operator
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "cHJvbS1vcGVyYXRvcg=="
  ldap-toml: ""
